### ISSUE TITLE
Worker für BuildMove darf nicht frei wählbar sein

### ISSUE THREAD

**Issue by 1451678** [kraemerstim/Santorini#11]
Derzeit kann der Spieler nach einem WorkerMove bei der Eingabe des BuildMoves über die Console den entsprechenden Worker auswählen. Dieser darf für den BuildMove allerdings nicht frei wählbar sein. Der Worker wurde durch den WorkerMove bereits definiert.

**Comment by kraemerstim** [comment]
Gefixt [hiermit](https://github.com/kraemerstim/Santorini/commit/ad2f5b02cd7efc0c23c40087b2f924178f55f59e)
