### ISSUE TITLE
Neue Issues anlegen

### ISSUE THREAD

**Issue by kraemerstim** [kraemerstim/Santorini#3]

**Comment by kraemerstim** [comment]
Finde ich sehr gut!

**Comment by 1451678** [comment]
Habe eins angelegt, jetzt bist du dran. ;)

Ich würde einfach sagen, jeder trägt das ein, was ihm auffällt. Die Issues kann sich dann ja nach und nach jeder einfach ziehen.

**Comment by kraemerstim** [comment]
Würde ich mal zumachen :)
